services:
  db:
    image: postgres:15
    container_name: sensor_db
    environment:
      POSTGRES_DB: sensor_db
      POSTGRES_USER: sensor_user
      POSTGRES_PASSWORD: sensor_pass123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - sensor_network
    restart: unless-stopped

  web:
    build: .
    container_name: sensor_api
    volumes:
      - ./app:/app
    ports:
      - "8002:8000"  # <--- Puerto 8002 en el host
    environment:
      DB_NAME: sensor_db
      DB_USER: sensor_user
      DB_PASSWORD: sensor_pass123
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db
    networks:
      - sensor_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  sensor_network:
    driver: bridge